@echo off
REM Wrapper that invokes awscli through the venv python, avoiding the broken
REM "File association not found for extension .py" noise from the stock aws.cmd.
REM
REM Usage:  Point kubeconfig exec.command at this file, or put its directory
REM         first in PATH so it shadows the system aws / aws.cmd.
REM
REM This file is auto-generated by the SparkPilot dev tooling.

setlocal

REM Prefer the venv python next to this script; fall back to PATH.
set "SCRIPT_DIR=%~dp0"
set "VENV_PYTHON=%SCRIPT_DIR%..\..\..\.venv\Scripts\python.exe"
if not exist "%VENV_PYTHON%" (
    set "VENV_PYTHON=%SCRIPT_DIR%..\..\.venv\Scripts\python.exe"
)
if not exist "%VENV_PYTHON%" (
    set "VENV_PYTHON=python"
)

"%VENV_PYTHON%" -m awscli %*
exit /B %ERRORLEVEL%
